# Generated by Django 6.0.2 on 2026-02-16 13:04

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Section",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Section name (e.g., 'Lavoro', 'Immobili')",
                        max_length=100,
                        unique=True,
                        verbose_name="name",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        help_text="URL-friendly identifier (auto-generated from name if blank)",
                        max_length=100,
                        unique=True,
                        verbose_name="slug",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Description of what this section is for",
                        verbose_name="description",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Icon identifier for frontend (e.g., 'briefcase', 'home')",
                        max_length=50,
                        verbose_name="icon",
                    ),
                ),
                (
                    "allowed_listing_types",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of allowed listing types: ['cerco', 'offro']",
                        verbose_name="allowed listing types",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Order in which sections appear (lower = first)",
                        verbose_name="display order",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Only active sections are shown to users",
                        verbose_name="active",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "section",
                "verbose_name_plural": "sections",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Listing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="title")),
                (
                    "listing_type",
                    models.CharField(
                        choices=[("cerco", "Cerco"), ("offro", "Offro")],
                        help_text="Whether you're seeking or offering",
                        max_length=10,
                        verbose_name="listing type",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Detailed description of your listing",
                        verbose_name="description",
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        help_text="Location (city, area, or 'Remote')",
                        max_length=200,
                        verbose_name="location",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Price or compensation (optional)",
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="price",
                    ),
                ),
                (
                    "price_negotiable",
                    models.BooleanField(default=False, verbose_name="price negotiable"),
                ),
                (
                    "contact_email",
                    models.EmailField(
                        blank=True,
                        help_text="Contact email (defaults to your account email if blank)",
                        max_length=254,
                        verbose_name="contact email",
                    ),
                ),
                (
                    "contact_phone",
                    models.CharField(
                        blank=True,
                        help_text="Contact phone (Italian format: +39XXXXXXXXX)",
                        max_length=13,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Phone number must be in format: '+39XXXXXXXXX' (Italian format)",
                                regex="^\\+39\\d{9,10}$",
                            )
                        ],
                        verbose_name="contact phone",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("archived", "Archived"),
                            ("expired", "Expired"),
                        ],
                        default="draft",
                        max_length=10,
                        verbose_name="status",
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When this listing expires (optional)",
                        null=True,
                        verbose_name="expires at",
                    ),
                ),
                (
                    "is_flagged",
                    models.BooleanField(
                        default=False,
                        help_text="Listing has been flagged for review",
                        verbose_name="flagged",
                    ),
                ),
                (
                    "flagged_reason",
                    models.TextField(blank=True, verbose_name="flag reason"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "published_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="published at"
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="listings",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="author",
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="listings",
                        to="bulletin.section",
                        verbose_name="section",
                    ),
                ),
            ],
            options={
                "verbose_name": "listing",
                "verbose_name_plural": "listings",
                "ordering": ["-published_at", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "-published_at"],
                        name="bulletin_li_status_289f1f_idx",
                    ),
                    models.Index(
                        fields=["section", "status"],
                        name="bulletin_li_section_d09c08_idx",
                    ),
                    models.Index(
                        fields=["author", "status"],
                        name="bulletin_li_author__3a5fce_idx",
                    ),
                ],
            },
        ),
    ]
