# Generated by Django 6.0.2 on 2026-02-21 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='listing_type',
            field=models.CharField(blank=True, choices=[('cerco', 'Cerco'), ('offro', 'Offro')], help_text="Whether you're seeking or offering (optional for some sections)", max_length=10, null=True, verbose_name='listing type'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived'), ('expired', 'Expired')], default='published', max_length=10, verbose_name='status'),
        ),
    ]
