# Generated by Django 6.0.2 on 2026-02-21 17:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bulletin', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL, verbose_name='author'),
        ),
        migrations.AddField(
            model_name='listing',
            name='listing_type',
            field=models.ForeignKey(help_text='Type of listing (determines the section)', on_delete=django.db.models.deletion.PROTECT, related_name='listings', to='bulletin.listingtype', verbose_name='listing type'),
        ),
        migrations.AddField(
            model_name='listingtype',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listing_types', to='bulletin.section', verbose_name='section'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['status', '-published_at'], name='bulletin_li_status_289f1f_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['listing_type', 'status'], name='bulletin_li_listing_09936b_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['author', 'status'], name='bulletin_li_author__3a5fce_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='listingtype',
            unique_together={('section', 'value')},
        ),
    ]
