# Generated by Django 6.0.2 on 2026-02-21 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletin', '0002_make_listing_type_optional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='listing_type',
            field=models.CharField(blank=True, help_text="Type of listing (defined by section, e.g., 'cerco', 'offro', 'affitto')", max_length=50, null=True, verbose_name='listing type'),
        ),
        migrations.AlterField(
            model_name='section',
            name='allowed_listing_types',
            field=models.JSONField(blank=True, default=list, help_text='List of listing type objects: [{"value": "cerco", "label": "Cerco"}, {"value": "offro", "label": "Offro"}]. Empty list means no listing type required.', verbose_name='allowed listing types'),
        ),
    ]
