# Generated by Django 6.0.2 on 2026-02-21 16:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message="Phone number must be in format: '+39XXXXXXXXX' (Italian format)", regex='^\\+39\\d{9,10}$')], verbose_name='phone number'),
        ),
    ]
